### ISSUE TITLE
wpkg-gp behaves strange after successfull run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cleitet/wpkg-gp#89]
```
Hi everybody,
we are using wpkg-gp in a medium sized environment (approx. 50 boxes) and 
recognize some strange behavior all over this systems.


What steps will reproduce the problem?

1. fresh windows 7 x64 + wpkg-gp-0.15_x64.exe
2. run wpkg once - everything works as expected
3. run it again will result in failure


What is the expected output? What do you see instead?

The problem appears, after one successful run of wpkg-gp. On the server-side 
the connection gets interrupted, but if you try to run wpkg-gp on client side 
again it fails with the attached client debug log.
On the samba side there seems to be no issue:
connect to service reports initially as user wpkg (uid=1002, gid=1002) (pid 
17177)
closed connection to service wpkg
*after this point there is no more activity on samba side and the problem 
appears.
The failure situation stays for 10-30min, afterwards wpkg-gp will work again 
for one shot.


What version of the product are you using? On what operating system?

Mixed environment (Windows XP/7/x86/x64).

We checked for already used connections (net use) and excluded ipv6 as error 
source.

Debug log attached
```

Original issue reported on code.google.com by `icygro...@gmail.com` on 11 Apr 2012 at 2:07

Attachments:
- [client log.txt](https://storage.googleapis.com/google-code-attachments/wpkg-gp/issue-89/comment-0/client log.txt)

**Comment by adelphi-company** [comment]
Did you ever found a solution for this?

Similar problem (works only once and again after ~30min) but different error message in log.
Windows 10 1903 and Windows Server 2016 connecting to Debian Buster SMB-Server v2.4.9

2019-08-14 12:30:54,193 - WpkgService - DEBUG - Trying to connect to share. 1 of 7
2019-08-14 12:30:54,270 - WpkgService - ERROR - Error when processing Named Pipe Client:
Traceback (most recent call last):
  File "WpkgServer.pyc", line 214, in DoProcessClient
  File "WpkgExecuter.pyc", line 101, in Query
  File "WpkgNetworkHandler.pyc", line 88, in connect_to_network_share
error: (67, 'WNetAddConnection2', 'Network name not found')
